name: Pipeline de CI - evaluation-service

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: FIAP-Teach-Challenge-2/toggle-master-ci/.github/workflows/reusable-ci-go.yml@main
    with:
      service-name: evaluation-service
      ecr-repository: togglemaster/evaluation-service
    secrets: inherit
